### ISSUE TITLE
Defining multiple translations with same language is not forbidden.

### ISSUE THREAD

**Issue by aloiscochard** [propensive/rapture-i18n#2]
Suprisingly (or not - if you know it's encoded with subtyping), the following invalid definition compile:

```
  val greeting = en"Hello" | fr"Bonjour" | en"Hey"
```

**Comment by aloiscochard** [comment]
Trying to use seems to always return the last translation, not sure how predictable that is.

**Comment by propensive** [comment]
Good point. It will always use the last one, but I think the `|` operator could add a constraint to make this a type error. It might require a macro, but I'll investigate.

**Comment by propensive** [comment]
This has been improved as much as I believe is possible without using macros. I've added a patch such that `en"hello" | fr"bonjour" | en"hi"` is now illegal (by virtue of ambiguous implicits), whereas `en"hello" | fr"bonjour" | (de"guten Tag" | en"hi")` would still be legal.
